import React from "react";
import Head from "next/head";
import CardList from "../components/CardList";
import CardItem from "../components/CardItem";
import { useSelector } from "react-redux";

export default function Bookmark() {
  const { bookmarkedMovies, bookmarkedSeries } = useSelector(
    (state: any) => state.movies
  );
  return (
    <div>
      <Head>
        <title>Movie Entertainment App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-slate-900 text-white min-h-screen">
        <div className="flex flex-col py-28 lg:pt-4 lg:pl-32 gap-8">
          <div className="max-w-7xl mx-auto px-8 font-extralight">
            <h1 className="mb-4 text-3xl">Movie</h1>
            <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6 md:gap-10">
              {bookmarkedMovies.map((movie: any) => (
                <CardItem key={movie.id} {...movie} />
              ))}
            </div>
          </div>

          <div className="max-w-7xl mx-auto px-8 font-extralight">
            <h1 className="mb-4 text-3xl">TV Series</h1>
            <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6 md:gap-10">
              {bookmarkedSeries.map((series: any) => (
                <CardItem key={series.id} {...series} />
              ))}
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
