import React from "react";
import Head from "next/head";
import CardList from "../components/CardList";
import fetchData from "../utils/fetcher";
import { Data } from "../models";

interface DataProps {
  films: Data[];
}

export default function Bookmark({ films }: DataProps) {
  const bookmarkedFilms = films.filter(
    (film) => film.category === "Movie" && film.isBookmarked === true
  );
  const bookmarkedSeries = films.filter(
    (film) => film.category === "TV Series" && film.isBookmarked === true
  );

  return (
    <div>
      <Head>
        <title>Movie Entertainment App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-slate-900 text-white min-h-screen">
        <div className="flex flex-col py-28 lg:pt-4 lg:pl-32 gap-8">
          <CardList title="Bookmarked Movies" films={bookmarkedFilms} />
          <CardList title="Bookmarked TV Series" films={bookmarkedSeries} />
        </div>
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const films = await fetchData();

  return {
    props: { films },
  };
}
