import Head from "next/head";
import Recommendation from "../components/Recommendation";
import Trending from "../components/Trending";
import { Film } from "../models";
interface FilmProps {
  films: Film[];
}

export default function Home({ films }: FilmProps) {
  const trendingFilms: Film[] = films.filter(
    (film) => film.isTrending === true
  );
  const recommendedFilms: Film[] = films.filter(
    (film) => film.isTrending === false
  );

  return (
    <div>
      <Head>
        <title>Movie Entertainment App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-slate-900 text-white">
        <div className="pt-40 lg:pl-32">
          <Trending trendingFilms={trendingFilms} />
          <Recommendation recommendedFilms={recommendedFilms} />
        </div>
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const res = await fetch("http://localhost:3000/data.json");
  const films = await res.json();

  return {
    props: { films },
  };
}
