import React, { useState } from "react";
import Head from "next/head";
import { useSelector } from "react-redux";
import CardList from "../components/CardList";
import SearchBox from "../components/SearchBox";
import { Data } from "../models";

export default function Movies() {
  const [searchQuery, setSearchQuery] = useState("");

  const { movies } = useSelector((state: any) => state.movies);
  const allMovies = movies.filter((item: any) => item.category === "Movie");

  const filteredMovies = movies.filter((element: Data) =>
    element.title.toLowerCase().includes(searchQuery)
  );

  console.log(filteredMovies);

  return (
    <div>
      <Head>
        <title>Movies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-slate-900 text-white min-h-screen">
        <div className="py-28 lg:pt-4 lg:pl-32">
          <SearchBox
            placeholder="Search for movies"
            setSearchQuery={setSearchQuery}
          />

          {searchQuery ? (
            <CardList
              title={`Found ${filteredMovies.length} ${
                filteredMovies.length > 1 ? "results" : "result"
              } for '${searchQuery}'`}
              films={filteredMovies}
            />
          ) : (
            <>
              <CardList title="Movies" films={allMovies} />
            </>
          )}
        </div>
      </main>
    </div>
  );
}
