import React, { useState } from "react";
import Head from "next/head";
import CardList from "../components/CardList";
import SearchBox from "../components/SearchBox";
import fetchData from "../utils/fetcher";
import { Data } from "../models";
interface MovieProps {
  movies: Data[];
}

export default function Movies({ movies }: MovieProps) {
  const [searchQuery, setSearchQuery] = useState("");

  const filteredMovies = movies.filter((element) =>
    element.title.toLowerCase().includes(searchQuery)
  );

  return (
    <div>
      <Head>
        <title>Movies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-slate-900 text-white min-h-screen">
        <div className="py-28 lg:pt-4 lg:pl-32">
          <SearchBox
            placeholder="Search for movies"
            setSearchQuery={setSearchQuery}
          />

          {searchQuery ? (
            <CardList
              title={`Found ${filteredMovies.length} ${
                filteredMovies.length > 1 ? "results" : "result"
              } for '${searchQuery}'`}
              films={filteredMovies}
            />
          ) : (
            <>
              <CardList title="Movies" films={movies} />
            </>
          )}
        </div>
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const data = await fetchData();
  const movies = data.filter((element: Data) => element.category === "Movie");

  return {
    props: { movies },
  };
}
