import React from "react";
import Head from "next/head";
import CardList from "../components/CardList";
import fetchData from "../utils/fetcher";
import { Data } from "../models";
interface MovieProps {
  movies: Data[];
}

export default function Movies({ movies }: MovieProps) {
  return (
    <div>
      <Head>
        <title>Movies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-slate-900 text-white min-h-screen">
        <div className="py-28 lg:pt-4 lg:pl-32">
          <CardList title="Movies" films={movies} />
        </div>
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const data = await fetchData();
  const movies = data.filter((element: Data) => element.category === "Movie");

  return {
    props: { movies },
  };
}
