import React, { useState } from "react";
import Head from "next/head";
import CardList from "../components/CardList";
import SearchBox from "../components/SearchBox";
import fetchData from "../utils/fetcher";
import { Data } from "../models";

interface SeriesProps {
  series: Data[];
}

export default function Series({ series }: SeriesProps) {
  const [searchQuery, setSearchQuery] = useState("");

  const filteredSeries = series.filter((element) =>
    element.title.toLowerCase().includes(searchQuery)
  );

  return (
    <div>
      <Head>
        <title>TV Series</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-slate-900 text-white min-h-screen">
        <div className="py-28 lg:pt-4 lg:pl-32">
          <SearchBox
            placeholder="Search for TV Series"
            setSearchQuery={setSearchQuery}
          />

          {searchQuery ? (
            <CardList
              title={`Found ${filteredSeries.length} ${
                filteredSeries.length > 1 ? "results" : "result"
              } for '${searchQuery}'`}
              films={filteredSeries}
            />
          ) : (
            <>
              <CardList title="Movies" films={series} />
            </>
          )}
        </div>
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const data = await fetchData();
  const series = data.filter(
    (element: Data) => element.category === "TV Series"
  );

  return {
    props: { series },
  };
}
